# Generated by Django 5.2.8 on 2025-11-19 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(blank=True, default='#2196f3', max_length=7),
        ),
        migrations.AddField(
            model_name='board',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
